handlers/main.yml
tasks/RedHat.yml

Zookeeper service had state=restarted which cause that every time
when playbook were run, Zookeeper restart.
Added restart handler added notifications to all config files and
changed state to "started".

Removed unneeded Zookeeper restart on every run

---

tasks/Debian.yml

Ansible were restarting Zookeeper every time Ansible were running.
Fixed service state=started and added restart handlers to restart
only if configuration changes.

Fixed Zookeeper to restart every time Ansible runs on Debian

---

defaults/main.yml

Builds will fail if using 3.4.6 for the version because Apache removes
old versions from their mirrors for some ungodly reason.

Bump default zookeeper_version to 3.4.7

---

defaults/main.yml

Apache has removed ZK 3.4.7 from their mirrors, causing builds to fail again.
I followed up in #zookeeper to see why these releases keep disappearing from the mirrors,
so hopefully we'll get some answers as to how to prevent this going forward.
```
$ curl http://www.us.apache.org/dist/zookeeper/zookeeper-3.4.7/zookeeper-3.4.7.tar.gz -I
HTTP/1.1 404 Not Found
Date: Wed, 13 Jan 2016 17:21:26 GMT
Server: Apache/2.4.7 (Ubuntu)
Content-Type: text/html; charset=iso-8859-1
```
```
$ curl http://www.us.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz -I
HTTP/1.1 200 OK
Date: Wed, 13 Jan 2016 17:21:31 GMT
Server: Apache/2.4.7 (Ubuntu)
Last-Modified: Sun, 10 Jan 2016 17:11:22 GMT
ETag: "10e11ea-528fde8dfe9ec"
Accept-Ranges: bytes
Content-Length: 17699306
Cache-Control: max-age=3600 …
```

Back to version 3.4.6

---

tasks/RedHat.yml

@JasonGiedymin 
It's already enabled for Debian https://github.com/AnsibleShipyard/ansible-zookeeper/blob/master/tasks/Debian.yml#L26 but somehow missed on RedHat.

Make zookeeper service enabled for RedHat

---

.travis.yml
ci/hosts_hash.yml
ci/hosts_list.yml
defaults/main.yml
templates/myid.j2
templates/zoo.cfg.j2

@AnsibleShipyard/developers 
cc @sumantmurke (since I had this as dirty master for few weeks, decided to step in) @stevelle
This originates to https://github.com/ernestas-poskus/ansible-zookeeper/pull/1
> All host had zoo_id as 1 by default as it used from default template hence all
the zookeeper nodes were not able to work with each other.
This fix will help operators to specify server id for host. This will help
them to configure the multinode zookeeper
Also cleaned up zoo.conf by replacing use of loop.index to use of server.id
for full consistency.
I went step further and made hosts to accept both list & hash for convenience 
This allows to manipulate hosts in a following manner:
```yaml
- name: Zookeeper
hosts: zookeepers
sudo: yes
roles:
- role: ansible-zookeeper
zookeeper_hosts: …
```

Allow zookeeper hosts to accept list and hash

---

.travis.yml

On new release this hook will reimport role on Ansible Galaxy else it must be done manually.
https://galaxy.ansible.com/AnsibleShipyard/ansible-zookeeper/
Intentionally not bumping version since this change does not affect role

Add Ansible Galaxy webhook

---

defaults/main.yml
meta/main.yml
tasks/Debian-tarball.yml
tasks/deb-uninstall.yml
tasks/main.yml
templates/zookeeper.conf.j2

final PR to fix: https://github.com/AnsibleShipyard/ansible-zookeeper/issues/26
thx for review @ernestas-poskus 
Update: We could also extract the 2 'configure' tasks from tarball.yml, and re-use the same include file also in the old Debian.yml installation, to further reduce code duplication. Should I do in this PR?

Zookeeper setup using offical tarball (also) on debian/ubuntu

---

tasks/Debian-tarball.yml
tasks/Debian.yml
tasks/RedHat.yml
tasks/common-config.yml

removes duplication by re-using the same task(s) in the common include
Note: Initially I planned to do the same for the 2 other config tasks (that write the 'myid' and 'zoo.cfg' files).
Unfortunately in the Debian(using apt) case, those 2 files are written in the zookeeper conf folder where-as for the redhat/debian-tarball case the `myid` gets written into the `data_dir` ).
In order to achieve this, we would require to introduce extra variables, that define the deploy path for these 2 files, and overwrite their default value for ex. for the debian(apt) case (for ex. using an vars include). 
Not sure if it's worth the trouble? (IMO no, in case debian(apt) support would be removed at some point)
@ernestas-poskus ?

Refactor the service init task into the common include

---

defaults/main.yml
tasks/tarball.yml

optional/configurable registration of the zkCli (and other zookeeper tools) to the system's PATH
disabled by default
Note: this feature isn't enabled for the (old)debian installation, because the default `zookeeper_dir`
setting is not applying here (it should be `/usr/share/zookeeper`).

Register the zookeeper bin dir in the PATH env variable

---

README.md
defaults/main.yml
tasks/Debian.yml
tasks/common-config.yml

Debian package uses different locations than assumed by the role.
This PR fixes this issue, without breaking the tarbal and RedHat locations/support.
A `zookeeper_conf_dir` variable is added to make the configuration location configurable, the default is set to `zookeeper_dir` (which was the hardcoded configuration location)
When `zookeeper_debian_apt_install` is true, the defaults are changed according to the Debian package locations.
If a users has other needs the default can be overridden by the user.

Debian package support

---

handlers/main.yml

Reloading the service configuration(s) must be done before (re)starting the services in order for the configuration changes to be picked up.
Additionally, the `enabled=yes` parameter is already set in tasks/common-config.yml so it is removed

Make sure daemon-reload is executed first

---

tasks/common-config.yml

When installing zookeeper it gets (re)started twice, as enabling the service also starts it.
After the role finished the handler also (re)starts the service again.
By removing the optional (when `enabled` is used) `state` parameter it does not start at this at this task (but when the role finished), preventing (re)starting twice.

Let handler (re)start zookeeper

---

README.md
defaults/main.yml
tasks/Debian.yml

by allowing to configure a custom (ppa) apt repos, we can use a community provided v3.4.8 deb-pkg based deployment  (which is more secure than using 'tarball' , when later installing `mesos`  which by default has 'zookeeper' in its dependencies).
Example config to make this work:
```
zookeeper_debian_apt_repository: "ppa:ufscar/zookeeper"
zookeeper_debian_apt_install: true
zookeeper_version: 3.4.8
```

Support custom zookeeper debian apt repository (to use v3.4.8 on Ubuntu 14.04

---

defaults/main.yml

Currently, when running ansible-zookeeper role on Debian 8 host, it
fails:
TASK [AnsibleShipyard.ansible-zookeeper : Enable zookeeper service] 
***************************************************
fatal: [debian8-host]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service zookeeper: host"}
This happens because `zookeeper_debian_systemd_enabled` variable is
enabled only for Ubuntu >= 15.04 hosts.
This PR adds check for Debian >= 8.0, so Zookeeper successfully installs
on Debian 8.0

Enable systemd service for Debian 8

---

tasks/tarball.yml

The latest Zookeeper version 3.5.3-beta is distributed as plain tar
archive, so `tar zxf` fails with `gzip: stdin: not in gzip format`.
Also, recent versions of tar recognize format by itself, so there is no
need in 'z' option.

Remove 'z' from untar command

---

.travis.yml

Due to failing build
```
The command "sudo apt-get install docker-engine=$DOCKER_VERSION -yq --no-install-suggests --no-install-recommends --force-yes -o Dpkg::Options::="--force-confnew"" failed and exited with 100 during .
```

Remove .travis specific docker version constraint

---

templates/zookeeper.service.j2

In order to avoid name-resolution and connectivity issues to other cluster nodes, especially when a server reboot occurs, make sure ZK only starts up after the network has started up properly.

Make ZK startup only after network is up

---

README.md
defaults/main.yml
templates/zoo.cfg.j2
tests/test.yml

Hi,
This playbook helped me a lot. That was just a little issue, that I could not setup custom ports for peer to peer node communication.
It was hardcoded to `2888:3888`. On my servers setup these ports are not accessible, so I needed to use another. I think that option to override those ports may be usefull.
Thanks!

Extracted hardcoded zookeeper ports into vars

---

README.md
defaults/main.yml
templates/myid.j2
tests/test.yml

There are sometimes when `inventory_hostname` is not the real hostname of your machine, and you want to specify which fact from ansible represents better your hostname.
For this I added `zookeeper_own_hostname` which by default equals to `inventory_hostname` but let you for instance overwrite it by `ansible_nodename` or whatever other variable or value you need.
This change is backwards compatible.

Customize own hostname with a new variable
